name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Pages
        run: |
          mkdir docs

          curl -Ls "https://github.com/live-codes/livecodes/releases/download/v45/livecodes-v45.tar.gz" | tar -xz
          mv build docs/livecodes

          mv index.html docs/

          mkdir docs/examples
          cd examples
          for NAME in *; do
            if [ -f "$NAME" ] -a [[ $NAME == *.html ]]; then
              echo "<meta http-equiv=\"refresh\" content = \"0;url=https://versatiles.org/playground/livecodes/?x=https%3A%2F%2Fgithub.com%2Fversatiles-org%2Fplayground%2Ftree%2Fmain%2Fexamples%2F${NAME}\">" > "../docs/examples/${NAME}"
            fi
          done

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
