name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Pages
        run: |
          mkdir docs

          # add LiveCodes
          curl -Ls "https://github.com/live-codes/livecodes/releases/download/v45/livecodes-v45.tar.gz" | tar -xz
          mv build docs/livecodes

          # add playground page
          mv index.html docs/

          # replace examples with correct redirects to livecodes
          mkdir docs/examples
          cd examples
          for FILE in *; do
            NAME=${FILE%%.*}
            if [[ -f "$NAME.json" ]]; then
              mkdir "../docs/examples/$NAME"
              mv "$NAME.json" "../docs/examples/$NAME.json"
              echo "<html><head><meta http-equiv=\"refresh\" content = \"0;url=https://versatiles.org/playground/livecodes/?config=https://versatiles.org/playground/examples/$NAME.json\"></head></html>" > "../docs/examples/$NAME/index.html"
            fi
          done
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
